<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>gix</ToolCommandName>
  </PropertyGroup>
<PropertyGroup>
    <Version>1.0.2</Version>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
    <Description></Description>
    <Company>Iciclecreek</Company>
    <Authors>Tom Laird-McConnell</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/tomlm/Gix</PackageProjectUrl>
    <PackageIconUrl>https://raw.githubusercontent.com/tomlm/Gix/master/icon.png</PackageIconUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <RepositoryUrl>https://github.com/tomlm/Gix</RepositoryUrl>
    <Copyright>Tom Laird-McConnell All Rights Reserved</Copyright>
    <RootNamespace>Gix</RootNamespace>
    <ContentTargetFolders>content</ContentTargetFolders>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>  
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageTags></PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="" />
    <None Include="../../icon.png" Pack="true" PackagePath="" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
