<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>six</ToolCommandName>
  </PropertyGroup>
  <PropertyGroup>
    <Version>1.0.3</Version>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <Description></Description>
    <Company>Iciclecreek</Company>
    <Authors>Tom Laird-McConnell</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/tomlm/Six</PackageProjectUrl>
    <PackageIconUrl>https://raw.githubusercontent.com/tomlm/Six/master/icon.png</PackageIconUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <RepositoryUrl>https://github.com/tomlm/Six</RepositoryUrl>
    <Copyright>Tom Laird-McConnell All Rights Reserved</Copyright>
    <RootNamespace>Six</RootNamespace>
    <ContentTargetFolders>content</ContentTargetFolders>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageTags></PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="" />
    <None Include="../../icon.png" Pack="true" PackagePath="" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="JeremyAnsel.ColorQuant" Version="3.0.74" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
  </ItemGroup>

</Project>
